version: "3.4"
services:
  my_backend:
    container_name: my_backend
    image: node:lts
    working_dir: /home/github/Back/quizzapi
    entrypoint: ["npm", "run", "start"]
    ports:
      - 3000:3000
    volumes:
      - .:/home/github/Back/quizzapi
    tty: true
