version: '3.5'

services:
  app:
    container_name: quizz_back
    ports:
      - '3000:3000'
    image: node:lts
    working_dir: /home/github/Back
    entrypoint: ["npm", "run", "start"]
    volumes:
      - .:/home/github/Back
      - /home/github/Front/certbot/conf:/home/github/Back/dist/certs
    extra_hosts:
      - 'host.docker.internal:host-gateway'