version: '3.5'

services:
  app:
    container_name: quizz_back
    ports:
      - '3000:3000'
    image: node:lts
    working_dir: /home/github/Front
    entrypoint: ["npm", "run", "start"]
    volumes:
      - .:/app
      - /home/github/Front/certbot/conf:/app/certs